export const countryLanguageCodes = [
  "fr",
  "en",
  "de",
  "es",
  "it",
  "pt",
  "nl",
  "pl",
  "ru",
  "zh",
  "ja",
  "ko",
  "ar",
  "cn",
] as const;

export type CountryLanguageCode = (typeof countryLanguageCodes)[number];

export const countryToLanguage = {
  AD: "es",
  AE: "ar",
  AF: "ar",
  AG: "en",
  AI: "en",
  AL: "en",
  AM: "ru",
  AO: "pt",
  AQ: "en",
  AR: "es",
  AS: "en",
  AT: "de",
  AU: "en",
  AW: "nl",
  AX: "en",
  AZ: "ru",
  BA: "en",
  BB: "en",
  BD: "en",
  BE: "fr",
  BF: "fr",
  BG: "en",
  BH: "ar",
  BI: "fr",
  BJ: "fr",
  BL: "fr",
  BM: "en",
  BN: "en",
  BO: "es",
  BQ: "nl",
  BR: "pt",
  BS: "en",
  BT: "en",
  BV: "en",
  BW: "en",
  BY: "ru",
  BZ: "en",
  CA: "en",
  CC: "en",
  CD: "fr",
  CF: "fr",
  CG: "fr",
  CH: "fr",
  CI: "fr",
  CK: "en",
  CL: "es",
  CM: "fr",
  CN: "zh",
  CO: "es",
  CR: "es",
  CU: "es",
  CV: "pt",
  CW: "nl",
  CX: "en",
  CY: "en",
  CZ: "en",
  DE: "de",
  DJ: "fr",
  DK: "en",
  DM: "en",
  DO: "es",
  DZ: "ar",
  EC: "es",
  EE: "en",
  EG: "ar",
  EH: "ar",
  ER: "ar",
  ES: "es",
  ET: "en",
  FI: "en",
  FJ: "en",
  FK: "en",
  FM: "en",
  FO: "en",
  FR: "fr",
  GA: "fr",
  GB: "en",
  GD: "en",
  GE: "ru",
  GF: "fr",
  GG: "en",
  GH: "en",
  GI: "en",
  GL: "en",
  GM: "en",
  GN: "fr",
  GP: "fr",
  GQ: "es",
  GR: "en",
  GS: "en",
  GT: "es",
  GU: "en",
  GW: "pt",
  GY: "en",
  HK: "zh",
  HM: "en",
  HN: "es",
  HR: "en",
  HT: "fr",
  HU: "en",
  ID: "en",
  IE: "en",
  IL: "en",
  IM: "en",
  IN: "en",
  IO: "en",
  IQ: "ar",
  IR: "ar",
  IS: "en",
  IT: "it",
  JE: "en",
  JM: "en",
  JO: "ar",
  JP: "ja",
  KE: "en",
  KG: "ru",
  KH: "en",
  KI: "en",
  KM: "fr",
  KN: "en",
  KP: "ko",
  KR: "ko",
  KW: "ar",
  KY: "en",
  KZ: "ru",
  LA: "en",
  LB: "ar",
  LC: "en",
  LI: "de",
  LK: "en",
  LR: "en",
  LS: "en",
  LT: "en",
  LU: "fr",
  LV: "en",
  LY: "ar",
  MA: "ar",
  MC: "fr",
  MD: "ru",
  ME: "en",
  MF: "fr",
  MG: "fr",
  MH: "en",
  MK: "en",
  ML: "fr",
  MM: "en",
  MN: "en",
  MO: "zh",
  MP: "en",
  MQ: "fr",
  MR: "ar",
  MS: "en",
  MT: "en",
  MU: "en",
  MV: "en",
  MW: "en",
  MX: "es",
  MY: "en",
  MZ: "pt",
  NA: "en",
  NC: "fr",
  NE: "fr",
  NF: "en",
  NG: "en",
  NI: "es",
  NL: "nl",
  NO: "en",
  NP: "en",
  NR: "en",
  NU: "en",
  NZ: "en",
  OM: "ar",
  PA: "es",
  PE: "es",
  PF: "fr",
  PG: "en",
  PH: "en",
  PK: "en",
  PL: "pl",
  PM: "fr",
  PN: "en",
  PR: "es",
  PS: "ar",
  PT: "pt",
  PW: "en",
  PY: "es",
  QA: "ar",
  RE: "fr",
  RO: "en",
  RS: "en",
  RU: "ru",
  RW: "fr",
  SA: "ar",
  SB: "en",
  SC: "fr",
  SD: "ar",
  SE: "en",
  SG: "en",
  SH: "en",
  SI: "en",
  SJ: "en",
  SK: "en",
  SL: "en",
  SM: "it",
  SN: "fr",
  SO: "ar",
  SR: "nl",
  SS: "en",
  ST: "pt",
  SV: "es",
  SX: "nl",
  SY: "ar",
  SZ: "en",
  TC: "en",
  TD: "fr",
  TF: "fr",
  TG: "fr",
  TH: "en",
  TJ: "ru",
  TK: "en",
  TL: "pt",
  TM: "ru",
  TN: "ar",
  TO: "en",
  TR: "en",
  TT: "en",
  TV: "en",
  TW: "zh",
  TZ: "en",
  UA: "ru",
  UG: "en",
  UM: "en",
  US: "en",
  UY: "es",
  UZ: "ru",
  VA: "it",
  VC: "en",
  VE: "es",
  VG: "en",
  VI: "en",
  VN: "en",
  VU: "fr",
  WF: "fr",
  WS: "en",
  YE: "ar",
  YT: "fr",
  ZA: "en",
  ZM: "en",
  ZW: "en",
} as const satisfies Record<string, CountryLanguageCode>;

const countryLocaleOverrides: Record<string, string> = {
  BE: "be_fr",
  CH: "ch_fr",
};

function normalizeCountryCode(country: string | null | undefined): string | null {
  if (!country) return null;

  const normalizedCountry = country.trim().toUpperCase();
  return normalizedCountry.length === 2 ? normalizedCountry : null;
}

export function getLanguageFromCountry(country: string | null | undefined): CountryLanguageCode | null {
  const countryCode = normalizeCountryCode(country);
  if (!countryCode) return null;

  return countryToLanguage[countryCode as keyof typeof countryToLanguage] ?? null;
}

export function getLocaleFromCountry<TLocale extends string>(
  country: string | null | undefined,
  availableLocales: readonly TLocale[],
  defaultLocale: TLocale
): TLocale {
  const countryCode = normalizeCountryCode(country);
  const regionalLocale = countryCode ? countryLocaleOverrides[countryCode] : null;

  if (regionalLocale && availableLocales.includes(regionalLocale as TLocale)) {
    return regionalLocale as TLocale;
  }

  const language = getLanguageFromCountry(countryCode);
  if (language && availableLocales.includes(language as TLocale)) {
    return language as TLocale;
  }

  if (language && language !== "fr" && availableLocales.includes("en" as TLocale)) {
    return "en" as TLocale;
  }

  return defaultLocale;
}
